spring.application.name=kiln-ai

spring.datasource.url=${KILN_DB_URL:jdbc:postgresql://localhost:5432/kiln_ai}
spring.datasource.username=${KILN_DB_USERNAME:kiln_ai}
spring.datasource.password=${KILN_DB_PASSWORD:kiln_ai}

spring.flyway.enabled=true

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-handlers-package=cn.lunalhx.ai.kilnai.infrastructure.adapter.repository

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
